apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  type: NodePort  # Definiše da se koristi NodePort servis
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
