apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: movie-service:latest
        imagePullPolicy: Never
        env:
        - name: EUREKA_SERVER_URL
          value: http://eureka-server:8761/eureka/
        - name: SERVER_PORT
          value: '30083'
        - name: MYSQL_SERVER_NAME
          value: 'mysql'
        - name: MYSQL_SERVER_PORT
          value: '3306'
        - name: MYSQL_SERVER_USERNAME
          value: 'movie'
        - name: MYSQL_SERVER_PASSWORD
          value: 'movie'
        - name: MYSQL_SERVER_DATABASE
          value: 'movie'
        ports:
        - containerPort: 30083
---

apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 30083
      targetPort: 30083
      nodePort: 30083
  type: LoadBalancer
