apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-service
  template:
    metadata:
      labels:
        app: cinema-service
    spec:
      containers:
      - name: cinema-service
        image: cinema-service:latest
        imagePullPolicy: Never
        env:
        - name: EUREKA_SERVER_URL
          value: http://eureka-server:8761/eureka/
        - name: SERVER_PORT
          value: '30082'
        - name: MYSQL_SERVER_NAME
          value: 'mysql'
        - name: MYSQL_SERVER_PORT
          value: '3306'
        - name: MYSQL_SERVER_USERNAME
          value: 'cinema'
        - name: MYSQL_SERVER_PASSWORD
          value: 'cinema'
        - name: MYSQL_SERVER_DATABASE
          value: 'cinema'
        ports:
        - containerPort: 30082
---

apiVersion: v1
kind: Service
metadata:
  name: cinema-service
spec:
  selector:
    app: cinema-service
  ports:
    - protocol: TCP
      port: 30082
      targetPort: 30082
      nodePort: 30082
  type: LoadBalancer
