apiVersion: v1
kind: Service
metadata:
  name: cinema-service
spec:
  type: NodePort
  selector:
    app: cinema-service
  ports:
    - port: 80
      targetPort: 8082  # Port na kojem mikroservis radi unutar Pod-a
      nodePort: 30007   # Port koji će biti dostupan spolja (može biti u opsegu 30000-32767)
      protocol: TCP
