apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        env:
        - name: EUREKA_SERVER_URL
          value: http://eureka-server:8761/eureka/
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVER_PORT
          value: '30081'
        - name: MYSQL_SERVER_NAME
          value: 'mysql'
        - name: MYSQL_SERVER_PORT
          value: '3306'
        - name: MYSQL_SERVER_USERNAME
          value: 'user'
        - name: MYSQL_SERVER_PASSWORD
          value: 'user'
        - name: MYSQL_SERVER_DATABASE
          value: 'user'
        ports:
        - containerPort: 30081
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 30081
      targetPort: 30081
      nodePort: 30081
  type: LoadBalancer

