apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-gateway
  template:
    metadata:
      labels:
        app: cinema-gateway
    spec:
      containers:
      - name: cinema-gateway
        image: cinema-gateway:latest
        imagePullPolicy: Never
        env:
        - name: EUREKA_SERVER_URL
          value: http://eureka-server:8761/eureka/
        - name: SERVER_PORT
          value: '30000'
        - name: SERVER-PUBLIC-IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 30000
---

apiVersion: v1
kind: Service
metadata:
  name: cinema-gateway
spec:
  selector:
    app: cinema-gateway
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
  type: LoadBalancer
